name: build

env:
  LINKERD_VERSION: 2.6.1
  LINKERD_VERSION_PREFIX: stable

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: choco pack
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: pack bin/win/linkerd.nuspec
    - name: upload nupkg file
      uses: actions/upload-artifact@v1
      with:
        name: linkerd-${{ env.LINKERD_VERSION_PREFIX }}-${{ env.LINKERD_VERSION }}.nupkg
        path: linkerd.${{ env.LINKERD_VERSION }}.nupkg
